# Generated by Django 4.0.1 on 2022-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='en_text1',
            new_name='en_text',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='en_text2',
            new_name='ru_text',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='ru_text1',
            new_name='uz_text',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='ru_text2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='uz_text1',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='uz_text2',
        ),
        migrations.AlterField(
            model_name='daytask',
            name='abed_dieta',
            field=models.ManyToManyField(blank=True, related_name='dieta_time2', to='API.TaskDieta'),
        ),
        migrations.AlterField(
            model_name='daytask',
            name='abed_sport',
            field=models.ManyToManyField(blank=True, related_name='sport_time2', to='API.TaskSport'),
        ),
        migrations.AlterField(
            model_name='daytask',
            name='ertalab_dieta',
            field=models.ManyToManyField(blank=True, related_name='dieta_time1', to='API.TaskDieta'),
        ),
        migrations.AlterField(
            model_name='daytask',
            name='ertalab_sport',
            field=models.ManyToManyField(blank=True, related_name='sport_time1', to='API.TaskSport'),
        ),
        migrations.AlterField(
            model_name='daytask',
            name='kechki_dieta',
            field=models.ManyToManyField(blank=True, related_name='dieta_time3', to='API.TaskDieta'),
        ),
        migrations.AlterField(
            model_name='daytask',
            name='kechki_sport',
            field=models.ManyToManyField(blank=True, related_name='sport_time3', to='API.TaskSport'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='task_dieta_can_not',
            field=models.ManyToManyField(blank=True, related_name='NoDieta', to='API.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='task_sport_can_not',
            field=models.ManyToManyField(blank=True, to='API.Sport'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
