# Generated by Django 4.0.1 on 2022-06-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_typeill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('telegram', models.URLField()),
                ('application', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='application',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='telegram',
        ),
    ]
