# Generated by Django 4.0.1 on 2022-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_comment_new_normal_delete_day_product_kaloriya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='en_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advice',
            name='en_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advice',
            name='ru_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advice',
            name='ru_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='en_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='ru_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='en_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='en_text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='en_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='ru_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='ru_text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='ru_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='en_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ru_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='en_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='ru_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
