# Generated by Django 4.0.4 on 2022-06-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_questionanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='answer',
            new_name='answer_en',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='question',
            new_name='answer_ru',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
