# Generated by Django 4.0.1 on 2022-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_footer_remove_infoaboutus_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='info/')),
                ('uz_text1', models.TextField()),
                ('en_text1', models.TextField()),
                ('ru_text1', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='en_text1',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='en_text2',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='ru_text1',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='ru_text2',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='uz_text1',
        ),
        migrations.RemoveField(
            model_name='infoaboutus',
            name='uz_text2',
        ),
        migrations.AddField(
            model_name='infoaboutus',
            name='array',
            field=models.ManyToManyField(to='API.AboutUs'),
        ),
    ]
