# Generated by Django 4.0.1 on 2022-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_aboutus_remove_infoaboutus_en_text1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('text_uz', models.TextField()),
                ('text_en', models.TextField()),
                ('text_ru', models.TextField()),
                ('img', models.ImageField(upload_to='static/search/')),
            ],
        ),
    ]
