# Generated by Django 4.0.1 on 2022-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_user_going_to_loss_day_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='healthapp/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('text2', models.CharField(max_length=255)),
                ('en_title', models.CharField(max_length=255)),
                ('en_text', models.TextField()),
                ('en_text2', models.CharField(max_length=255)),
                ('ru_title', models.CharField(max_length=255)),
                ('ru_text', models.TextField()),
                ('ru_text2', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='healthapp/')),
            ],
        ),
    ]
