# Generated by Django 4.0.1 on 2022-06-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_answer_questionanswer_answer_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogram',
            name='last_update',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
