# Generated by Django 4.0.1 on 2022-05-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_healthapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthapp',
            old_name='en_text2',
            new_name='text2_en',
        ),
        migrations.RenameField(
            model_name='healthapp',
            old_name='en_title',
            new_name='text2_ru',
        ),
        migrations.RenameField(
            model_name='healthapp',
            old_name='ru_text2',
            new_name='text2_uz',
        ),
        migrations.RenameField(
            model_name='healthapp',
            old_name='en_text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='healthapp',
            old_name='ru_text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='healthapp',
            old_name='text',
            new_name='text_uz',
        ),
        migrations.RenameField(
            model_name='healthapp',
            old_name='ru_title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='healthapp',
            old_name='text2',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='healthapp',
            old_name='title',
            new_name='title_uz',
        ),
    ]
