# Generated by Django 4.0.1 on 2022-05-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_en_text2_healthapp_text2_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='en_text2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='ru_text2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='text2',
        ),
    ]
