# Generated by Django 4.0.1 on 2022-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_footer_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
