# Generated by Django 4.0.1 on 2022-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_aboutus_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
