# Generated by Django 4.0.1 on 2022-06-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_weeklyprogram_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historytask',
            old_name='afternoon',
            new_name='afternoon_diet',
        ),
        migrations.RenameField(
            model_name='historytask',
            old_name='morning',
            new_name='afternoon_sport',
        ),
        migrations.RenameField(
            model_name='historytask',
            old_name='night',
            new_name='morning_diet',
        ),
        migrations.AddField(
            model_name='historytask',
            name='morning_sport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historytask',
            name='night_diet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historytask',
            name='night_sport',
            field=models.BooleanField(default=False),
        ),
    ]
