# Generated by Django 4.0.1 on 2022-06-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_rename_afternoon_historytask_afternoon_diet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daytask',
            old_name='abed_dieta',
            new_name='afternoon_diet',
        ),
        migrations.RenameField(
            model_name='daytask',
            old_name='abed_sport',
            new_name='afternoon_sport',
        ),
        migrations.RenameField(
            model_name='daytask',
            old_name='ertalab_dieta',
            new_name='morning_diet',
        ),
        migrations.RenameField(
            model_name='daytask',
            old_name='ertalab_sport',
            new_name='morning_sport',
        ),
        migrations.RenameField(
            model_name='daytask',
            old_name='kechki_dieta',
            new_name='night_diet',
        ),
        migrations.RenameField(
            model_name='daytask',
            old_name='kechki_sport',
            new_name='night_sport',
        ),
    ]
