# Generated by Django 4.0.1 on 2022-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_rename_title_aboutus_title_en_aboutus_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='address',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
