# Generated by Django 4.0.1 on 2022-05-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='video',
            new_name='network',
        ),
    ]
