# Generated by Django 4.0.1 on 2022-06-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_rename_abed_dieta_daytask_afternoon_diet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardfastlosstype',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='cardfastlosstype',
            old_name='text_en1',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='cardfastlosstype',
            old_name='text_en2',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='cardfastlosstype',
            old_name='text_ru1',
            new_name='text_uz',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='text_ru2',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='text_uz1',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='text_uz2',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='title_en1',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='title_en2',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='title_ru1',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='title_ru2',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='title_uz1',
        ),
        migrations.RemoveField(
            model_name='cardfastlosstype',
            name='title_uz2',
        ),
    ]
