# Generated by Django 4.0.1 on 2022-05-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_rename_video_user_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(max_length=350)),
                ('text_ru', models.CharField(max_length=350)),
                ('text_en', models.CharField(max_length=350)),
                ('img', models.ImageField(upload_to='motivation_letter/')),
            ],
        ),
    ]
