# Generated by Django 4.0.1 on 2022-06-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_rename_img1_cardfastlosstype_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytask',
            name='date',
            field=models.DateField(),
        ),
    ]
