# Generated by Django 4.0.1 on 2022-05-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_motivationletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivationletter',
            name='text_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='motivationletter',
            name='text_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='motivationletter',
            name='text_uz',
            field=models.TextField(),
        ),
    ]
