# Generated by Django 4.0.1 on 2022-05-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_motivationletter_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expert_type',
            field=models.IntegerField(choices=[(1, 'dietolog'), (2, 'sportsmen')], default=1),
        ),
    ]
