# Generated by Django 4.0.1 on 2022-05-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_user_expert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='task_dieta_can_not',
            field=models.ManyToManyField(blank=True, null=True, related_name='NoDieta', to='API.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='task_sport_can_not',
            field=models.ManyToManyField(blank=True, null=True, to='API.Sport'),
        ),
    ]
