# Generated by Django 4.0.1 on 2022-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_user_task_dieta_can_not_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kaloriya',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sport',
            name='kaloriya',
            field=models.FloatField(),
        ),
    ]
