# Generated by Django 4.0.4 on 2022-05-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_product_kaloriya_alter_sport_kaloriya'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastLost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fastlost/')),
                ('name_uz', models.CharField(blank=True, max_length=40, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('name_en', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
