# Generated by Django 4.0.4 on 2022-05-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_fastlost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='task_dieta_can_not',
            field=models.ManyToManyField(blank=True, related_name='NoDieta', to='API.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='task_sport_can_not',
            field=models.ManyToManyField(blank=True, to='API.sport'),
        ),
    ]
