# Generated by Django 4.0.4 on 2022-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_alter_user_task_dieta_can_not_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(blank=True, max_length=300, null=True)),
                ('text_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('text_en', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('music', models.FileField(upload_to='music')),
            ],
        ),
    ]
