# Generated by Django 4.0.1 on 2022-05-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_dailymotivation_weeklymusic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='task_dieta_can_not',
            field=models.ManyToManyField(blank=True, related_name='NoDieta', to='API.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='task_sport_can_not',
            field=models.ManyToManyField(blank=True, to='API.Sport'),
        ),
    ]
