# Generated by Django 4.0.1 on 2022-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_alter_user_task_dieta_can_not_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymusic',
            name='music',
            field=models.FileField(upload_to='music/'),
        ),
    ]
