# Generated by Django 4.0.1 on 2022-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_alter_weeklymusic_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal',
            name='female_weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
