# Generated by Django 4.0.1 on 2022-05-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_normal_female_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_title', models.CharField(max_length=255)),
                ('en_title', models.CharField(max_length=255)),
                ('ru_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='advice',
            old_name='en_title',
            new_name='uz_text',
        ),
        migrations.RemoveField(
            model_name='advice',
            name='ru_title',
        ),
        migrations.RemoveField(
            model_name='advice',
            name='text',
        ),
        migrations.RemoveField(
            model_name='advice',
            name='title',
        ),
    ]
