# Generated by Django 4.0.1 on 2022-06-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_titleadvice_rename_en_title_advice_uz_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='taskdieta',
            old_name='night',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='taskdieta',
            name='client',
        ),
        migrations.RemoveField(
            model_name='taskdieta',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='taskdieta',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='taskdieta',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='tasksport',
            name='client',
        ),
        migrations.AddField(
            model_name='taskdieta',
            name='grams',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdieta',
            name='total_calories',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksport',
            name='total_calories',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chorshanba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day3', to='API.daytask')),
                ('dushanba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day1', to='API.daytask')),
                ('juma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day5', to='API.daytask')),
                ('payshanba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day4', to='API.daytask')),
                ('seshanba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day2', to='API.daytask')),
                ('shanba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day6', to='API.daytask')),
                ('yakshanba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day7', to='API.daytask')),
            ],
        ),
        migrations.AddField(
            model_name='daytask',
            name='abed_dieta',
            field=models.ManyToManyField(blank=True, related_name='dieta_time2', to='API.TaskDieta'),
        ),
        migrations.AddField(
            model_name='daytask',
            name='abed_sport',
            field=models.ManyToManyField(blank=True, related_name='sport_time2', to='API.TaskSport'),
        ),
        migrations.AddField(
            model_name='daytask',
            name='ertalab_dieta',
            field=models.ManyToManyField(blank=True, related_name='dieta_time1', to='API.TaskDieta'),
        ),
        migrations.AddField(
            model_name='daytask',
            name='ertalab_sport',
            field=models.ManyToManyField(blank=True, related_name='sport_time1', to='API.TaskSport'),
        ),
        migrations.AddField(
            model_name='daytask',
            name='kechki_dieta',
            field=models.ManyToManyField(blank=True, related_name='dieta_time3', to='API.TaskDieta'),
        ),
        migrations.AddField(
            model_name='daytask',
            name='kechki_sport',
            field=models.ManyToManyField(blank=True, related_name='sport_time3', to='API.TaskSport'),
        ),
    ]
