# Generated by Django 4.0.1 on 2022-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_daytask_rename_night_taskdieta_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_title', models.CharField(max_length=555)),
                ('en_title', models.CharField(max_length=555)),
                ('ru_title', models.CharField(max_length=555)),
                ('img1', models.ImageField(upload_to='info/')),
                ('uz_text1', models.TextField()),
                ('en_text1', models.TextField()),
                ('ru_text1', models.TextField()),
                ('img2', models.ImageField(upload_to='info/')),
                ('uz_text2', models.TextField()),
                ('en_text2', models.TextField()),
                ('ru_text2', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('telegram', models.URLField()),
                ('application', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='daytask',
            name='weight_limit',
            field=models.IntegerField(default=1),
        ),
    ]
