# Generated by Django 4.0.1 on 2022-06-04 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_infoaboutus_daytask_weight_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('steps', models.IntegerField(default=0)),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.daytask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyMotivation',
        ),
        migrations.DeleteModel(
            name='WeeklyMusic',
        ),
        migrations.AddField(
            model_name='weeklyprogram',
            name='intended_weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
