from django.contrib import admin
from .models import *

# Register your models here.
# admin.site.register(Client)
admin.site.register(Product)
admin.site.register(Sport)
admin.site.register(TaskSport)
admin.site.register(TaskDieta)
admin.site.register(Comment)
admin.site.register(Advice)
admin.site.register(New)
admin.site.register(User)
admin.site.register(HistoryReyting)
admin.site.register(CategoryProduct)
admin.site.register(Normal)
admin.site.register(HealthApp)
# admin.site.register(MotivationLetter)
admin.site.register(FastLost)
# admin.site.register(InfoAboutUs)
#test
admin.site.register(WeeklyProgram)
admin.site.register(DayTask)
admin.site.register(HistoryTask)
admin.site.register(TypeIll)
admin.site.register(Footer)
admin.site.register(AboutUs)
admin.site.register(SearchStatic)
admin.site.register(CardFastLossType)
admin.site.register(QuestionAnswer)
