from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register('product', ProductViewSet)
router.register('sport', SportViewSet)
router.register('comment', CommentViewSet)
router.register('advice', AdviceViewSet)
router.register('new', NewViewSet)
router.register('homeheader', HealthAppViewSet)
router.register('category', CategoryProductViewSet)
# router.register('motivation_letter', MotivationLetterViewSet)
router.register('fastlost', FastLostView)
# router.register('info',InfoAboutUsView)
# router.register("day-motivation",DailyMotivationView)
# router.register("weekly-music",WeeklyMusicView)
router.register("ill",TypeIllViewSet)
router.register('footer', FooterViewSet)
router.register('aboutus', AboutUsViewSet)
router.register("search_static",SearchStaticViewSet)
router.register("cad_fast_loss",CardFastLossTypeViewSet)
